config:

  nginx_config:
    nginx_host: "localhost"
    nginx_port: 80
    nginx_protocol: "http"
    nginx_ssl: false
    #nginx_ssl_cert: "path/to/cert"
    #nginx_ssl_key: "path/to/key"

  user_interface_config:
    user_interface_hostname: "localhost"
    user_interface_listen_address: "127.0.0.1"
    user_interface_listen_port: 8080
    user_interface_protocol: "http"

  tor_settings:
    tor_enabled: true
    onion_address: "contiplatform.onion"
    tor_control_port: 9051
    tor_ssl: false
    #tor_ssl_cert: "path/to/cert"
    #tor_ssl_key: "path/to/key"

    

  
  duckdb_database_config:
    duckdb_database_host: "localhost"
    duckdb_database_port: 5432
    duckdb_database_name: "contiplatform"
    duckdb_database_user: "conti"
    duckdb_database_password: "randompassword"